### ISSUE TITLE
Variables with extra labels

### ISSUE THREAD

**Issue by sebaslarreap** [vanderbilt-data-science/lapop-dashboard#131]
Some variables have extra labels that does not correspond

**Comment by sebaslarreap** [comment]
The following list is based on the order these variables appear on Tableau
Variable 1 ambiente . Shows all responses as 0. Does not show labels
Variable 2 apoyo democratico. Shows labels 9 and 98 that don’t belong to variable
Variable 3. Apoyo democratico. Shows all responses as 100
Variable 4. Apoyo democratico. Shows all responses as 100
Variable 5. Apoyo democratico. Shows all responses as 100
Variable 6. Apoyo democratico. Shows all responses as 100
Variable 7. Apoyo democratico. Shows labels 10 and 98 that don’t correspond to variable
Variable 8. Apoyo democratico. Shows label 98 that does not correspond to variable
Variable 9. Apoyo democratico. Shows labels 88 and 98
Variable 10. Apoyo democratico. Shows all response as 100
Variable 11. Corrupcion. Shows labels 2 and 98
Variable 12. Corrupcion shows labels 2, 9, 88 and 98
Variable 13. Corrupcion shows labels 2, 9, and 98
Variable 14. Corrupcion shows labels 2, 9, and 98
Variable 15. Corrupcion shows labels 2, 9, and 98
Variable 16. Corrupcion shows labels 2, 9, 88, and 98
Variable 17. Corrupcion shows labels 2, 9, and 98
Variable 18. Corrupcion shows labels 2, 9, and 98
Variable 19. Corrupcion. Show label 98
Variable 20. Creencias. Shows only 100 responses
Variable 21. Economia. Shows label 98
Variable 22. Evaluaciones. Shows label 98
Variable 23. Evaluaciones shows label 98
Variable 24. Evaluaciones shows label 98
Variable 25. Evaluaciones shows label 98
Variable 26. Evaluaciones shows label 98
Variable 27. Evaluaciones shows label 98
Variable 28. Evaluaciones shows only label of 0 responses
Variable 29. Evaluaciones shows label 98
Variable 30. Evaluaciones shows label 98
Variable 31. Evaluaciones shows label 98
Variable 32. Evaluaciones shows label 98
Variable 33. Evaluaciones shows label  88 and 98
Variable 34. Evaluaciones shows label 98
Variable 35. Evaluaciones shows label 98
Variable 36. Evaluaciones shows label 98
Variable 37. Evaluaciones shows label 98
Variable 38. Evaluaciones shows label 98
Variable 39. Evaluaciones shows label 98
Variable 40. Genero shows only label of 100 responses
Variable 41. Genero shows only label of 100 responses
Variable 42. Migracion shows labels from 0 to 1200000 when should only show 0 and 100
Variable 43. Participacion civica shows only label 100
Variable 44. Participacion civica shows label 98
Variable 46. Participacion electoral shows label 98
Variable 47. Relaciones internacionales shows only responses of the 100 label. Should show from 0, 33, 66, and 100
Variable 48. Relaciones internacionales shows only responses of the 100 label. Should show from 0, 33, 66, and 100
Variable 49. Sociodem shows labels 2, 4, 5, and 90. Should only show 0 and 100
Variable 50. Sociodem. Only shows label 100. Should show labels 0 and 100
Variable 51. Sociodem. Shows label 2
Variable 52. Sociodem. Shows label 2 and 8
Variable 53. Sociodem. Does not show any data. 
Variable 54. Sociodem. Shows only label 100. Should have labels 0 and 100
Variable 55. Sociodem. Shows label 4
Variable 57. Sociodem shows label 2 and 3
Variable 59. Sociodem sows labels 2, 3, and 4
Variable 61. Tolerancia. Shows label 98
Variable 62. Tolerancia. Shows only label 0. Should have labels from 0 to 10
Variable 63. Tolerancia. Shows label 98
Variable 64. Tolerancia. Shows label 98
Variable 65. Tolerancia. Shows label 98
Variable 66. Tolerancia. Shows label 98
Variable 67. Tolerancia. Shows label 98

**Comment by maitagorri** [comment]
@sebaslarreap Can you try the new data set v10-1 and let me know what is still looking wrong? 
While checking that, it would be very helpful if you could record at least the short question wording after the category, since the category doesn't actually let me know which variable has the problem.

**Comment by sebaslarreap** [comment]
@maitagorri Updated the dataset but the errors persist. 

Here is the list of errors by each variable name: 
DST1B. Only shows 0 label
AOJ12. Shows 9 and 98 labels that does not correspond to variable
JC13. Only shows 100 label
JC10. Only shows 100 label
JC15A. Only shows 100 label
JC16A. Only shows 100 label
ING4. Shows 10 and 98 labels that does not correspond to variable
AOJ11. Shows label 98 that does not correspond
PN4. Shows label 88 and 98
VIC1EXT. Shows only 100 label
EXC6. Shows labels 2 and 98 as responses
EXC18. Shows labels 2, 9, 88, and 98 as responses
EXC13. Shows labels 2, 9, and 98 as responses
EXC16. Shows labels 2, 9, and 98 as responses
EXC14. Shows labels 2, 9, and 98 as responses
EXC15. Shows labels 2, 9, 88, and 98 as responses
EXC11. Shows labels 2, 9, and 98 as responses
EXC2. Shows labels 2, 9, and 98 as responses
EXC7. Shows label 98 as response
Q5B. Only shows label 100 as response
ROS4. Shows label 98 as response
M1. Shows label 98 as response
B13. Shows label 98 as response
B21A. Shows label 98 as response
B31. Shows label 98 as response
B32. Shows label 98 as response
B18. Shows label 98 as response
B47A. Only shows 0 as response
B12. Shows label 98 as response
B37. Shows label 98 as response
B21. Shows label 98 as response
IT1. Shows label 98 as response
B1. Shows label 88 and 98 as responses
EFF2. Shows label 98 as response
EFF1. Shows label 98 as response
B3. Shows label 98 as response
B4. Shows label 98 as response
B2. Shows label 98 as response
B6. Shows label 98 as response
VB50. Only shows label 100 as response
W14A. Only shows label 100 as response
Q10A. Shows values that does not correspond to variable
PROT3. Only shows label 100 as response
VB10. Shows label 98
POL1. Shows label 98
MIL10A. Only shows label 100 as response
MIL10E. Only shows label 100 as response
R12. Shows labels 2, 4, 5, and 90 that do not correspond to variable
CCT1B. Only shows label 100 as response
R15. Shows label 2
R14. Shows label 2 and 8
Q2. Variable no showing data
WF1. Only shows label 100 as response
R3. Shows label 4 
R4A. Shows labels 2 and 3
R1. Shows labels 2, 3, and 4
D1. Shows label 98
D6. Only shows label 0
D4. Shows label 98
D3. Shows label 98
D2. Shows label 98
D5. Shows label 98
E5. Shows label 98

Hope this helps.

**Comment by maitagorri** [comment]
@sebaslarreap Amazing, thank you!! (Too bad the errors are still there, but I'll get on fixing them.)
