### ISSUE TITLE
Null label on most variables

### ISSUE THREAD

**Issue by sebaslarreap** [vanderbilt-data-science/lapop-dashboard#132]
Should we keep this "Null" label in most of the variables displayed on the playground? In most of the cases the "Null" label has 0 cases.

**Comment by maitagorri** [comment]
I *think* this is something that happens in Tableau (no values are labeled "Null" in the dataset); could you look into this more @sebaslarreap ?

**Comment by sebaslarreap** [comment]
Got it. I just wanted to be sure that we do not want "null" to be as label. I fixed in Tableau. I hid it from displaying.
