### ISSUE TITLE
Variable average in the map

### ISSUE THREAD

**Issue by carolejwilson** [vanderbilt-data-science/lapop-dashboard#148]
The variable average in the map does not correspond to values of the variable?
If I select the first variable "Ambiente: Gastar...", all countries, 2018.  
The mean in the statistical summary box is 74.47, but the range in the map is 5.85-66.31 (highly unlikely given the overall average).
If I select Mexico only in 2018, the statistical summary box mean is 75.61 (seems right given the distribution), but the mean in the map is 17.77.  So not sure what's up with that.

**Comment by maitagorri** [comment]
Seems like a filter by year was only applied to a subset of dashes, not all of them--should be fixed
