### ISSUE TITLE
Split out Category and Question

### ISSUE THREAD

**Issue by jessespencersmith** [vanderbilt-data-science/lapop-dashboard#2]

**Comment by jessespencersmith** [comment]
This needs to be done in Tableau, if possible.

**Comment by jessespencersmith** [comment]
This is not possible on the R side for wide data.

**Comment by maitagorri** [comment]
Liz would like for this to be implemented eventually, possibly by students

**Comment by jessespencersmith** [comment]
Handled with shorter categories and questions
