### ISSUE TITLE
Add agegroup variable

### ISSUE THREAD

**Issue by maitagorri** [vanderbilt-data-science/lapop-dashboard#29]
Add age groups to data:
1. (min-25) 
2. (26-35) 
3. (36-45) 
4. (46-55) 
5. (56-65) 
6. (65+)

**Comment by jessespencersmith** [comment]
Use lookup into QWORD_2018_Core_10plus_countries(v1.0).csv
LAB_VAL_2018_Core_10plus_countries(v1.0).csv
in top-level project directory as outlined in #35 for this.

**Comment by jessespencersmith** [comment]
This coding is not included in the above tables. Should this be displayed as (0-25], (25,35], etc, or as 1, 2, 3, 4, 5, 6? Which graphs is it meant to be used with? If as a crosstab, need to move age to factors (or include as both factor and a measure)

**Comment by jessespencersmith** [comment]
Use the following as labels.

18-25
26-35
36-45
46-55
56-65
65+
