### ISSUE TITLE
Colors from branding guide

### ISSUE THREAD

**Issue by maitagorri** [vanderbilt-data-science/lapop-dashboard#30]
Bring dashboard into compliance with LAPOP brand colors (see image):
![LAPOP colors](https://user-images.githubusercontent.com/7852390/73090859-cd662600-3e9e-11ea-82e1-be4cf290aae8.PNG)

**Comment by jessespencersmith** [comment]
Create custom Tableau palette.

**Comment by jessespencersmith** [comment]
Colors recoded to match branding.
