### ISSUE TITLE
Data recoding

### ISSUE THREAD

**Issue by maitagorri** [vanderbilt-data-science/lapop-dashboard#32]
Get all data on a scale from 0-100

**Comment by jessespencersmith** [comment]
In R, use min and max for each variable (include categorical variables), this is the accepted approach (measurement issues aside). Convenience.

**Comment by jessespencersmith** [comment]
We need the full specification of the calculation.

**Comment by maitagorri** [comment]
@jessespencersmith, can you let us know what format you'd like the specification to be in? i.e. in a spreadsheet variable by variable, or something else?

**Comment by jessespencersmith** [comment]
Just a formula would work--just to confirmt that this is a scaling of the range from 0-100 (no standardization).

**Comment by maitagorri** [comment]
@jessespencersmith does this contain the necessary information? https://github.com/vanderbilt-data-science/lapop-dashboard/files/4187780/dash-recodes.xlsx

**Comment by jessespencersmith** [comment]
I believe so! I'll check against this after recoding. Recode numeric or ordinal answers to 0-100, inclusive, using the range (min-max), No centering.

**Comment by jessespencersmith** [comment]
Yes! I will use this to check the recoding. Record ordinal and quantitative measures to 0-100, inclusive, using min-max, no centering.

**Comment by jessespencersmith** [comment]
@carolejwilson will reexport as .csv's from Issue #35 with a versioned name. Note: this also address Issue #29 age group. Recode by joining.

**Comment by carolejwilson** [comment]
See csv's here #35

**Comment by jessespencersmith** [comment]
Answers differ from what is coded in csv's. (5,281 out of 621,842 don't match). Need to recode and carry question lname (e.g. a4, aoj11) forward from read. Right now they are dropped.

**Comment by jessespencersmith** [comment]
It is possible the unmatched are NAs OR a full country for a time period. Rerun anti-join and show @carolejwilson Friday
