### ISSUE TITLE
Show question wording with visualization

### ISSUE THREAD

**Issue by maitagorri** [vanderbilt-data-science/lapop-dashboard#33]

**Comment by jessespencersmith** [comment]
Variables are currently using variable name. The question wording is variable lable. Use lookup tables for variables, do join within Tableau, build sheet with full text.

**Comment by carolejwilson** [comment]
In the spreadsheet shared here: https://github.com/vanderbilt-data-science/lapop-dashboard/issues/35#issuecomment-584803064

**Comment by jessespencersmith** [comment]
Complete question wording now included in 0.2 dashboard
