### ISSUE TITLE
Weights

### ISSUE THREAD

**Issue by maitagorri** [vanderbilt-data-science/lapop-dashboard#34]
Confirm that weights are accurately implemented (where available)

**Comment by jessespencersmith** [comment]
Check results against gold set from Carole

**Comment by jessespencersmith** [comment]
Need to have a specification of the use of weights, and for which graphs should include weights and which should not. Compare to a traditionally generated set of data with weights applied.

**Comment by maitagorri** [comment]
See p. 5 [in our tech note](https://www.vanderbilt.edu/lapop/ab2016/AmericasBarometer_2016-17_Sample_Design.pdf):

2016/17 AmericasBarometer Survey: Weighting of country datasets
Most of the 2016/17 AmericasBarometer samples are self-weighted except for Bolivia, Guyana, Haiti, Peru, United State and Canada. Each country data set contains a variable called WT which is the “country weight” variable. In countries in which the sample is self-weighted, the value of each case = 1. When using this dataset for cross-country comparisons, in order to give each country in the study an identical weight in the pooled sample, LAPOP reweights each country data set in the merged files so that each country has an N of 1,500. The weight variable for cross-country comparisons is called “weight1500.” In SPSS, this is done via the “weight” command. Weights are already activated in SPSS datasets. In Stata, one should use the svyset command to weight the data and declare the sampling information to correctly compute standard errors that take into account the design effects. The command for single country, single year studies is: svyset upm [pw=wt], strata(estratopri). For cross-country and/or cross-time studies, the command is: svyset upm [pw=weight1500], strata(strata). These declarations have been made in Stata datasets. However, you must use the svy prefix with estimation commands to compute the weighted statistics and correct standard errors (see help svy_estimation within Stata for more information).
