### ISSUE TITLE
Double-check variables

### ISSUE THREAD

**Issue by maitagorri** [vanderbilt-data-science/lapop-dashboard#35]
Make sure the right variables are included in the dataset (Mariana has list)

**Comment by jessespencersmith** [comment]
Make sure all of the common variable determined by the R algo are the same as Mariana's list

**Comment by mariana-rodriguez** [comment]
[dash-recodes.xlsx](https://github.com/vanderbilt-data-science/lapop-dashboard/files/4187780/dash-recodes.xlsx)

Here's the list of vars, recodes and labels

**Comment by maitagorri** [comment]
@jessespencersmith @mariana-rodriguez does the list of recodes close this issue (if we have a list of variables to be included now)?

**Comment by carolejwilson** [comment]
The spreadsheet includes the full list of 162 variables, question wording, labels, and recodes.

**Comment by jessespencersmith** [comment]
We have a list of 69 questions which are in common between all of the files (excluding Columbia and Haiti). So, the full list of 162 variables include some variables that are specific to only a few countries. Why don't we change this issue to validating the list of common questions you suggest. It is only the common questions that will appear in the cross-country dashboards that we've identified for the next few sprints (there are plans for additional dashboards covering sinlge countries over time that might include variables specific to only that country, if I recall).

**Comment by jessespencersmith** [comment]
This lis of variables are the definitive list of variables to include in version 0.3. Force the inclusion of these, allow nulls when data not available.

**Comment by jessespencersmith** [comment]
Check to make sure it is possible to use the question wording will work for the filtering.

**Comment by carolejwilson** [comment]
Here are the two files in CSV format, with version numbers (v1.0) and informative names.
[Files_2018_Core_10plus_countries(v1.0).zip](https://github.com/vanderbilt-data-science/lapop-dashboard/files/4201026/Files_2018_Core_10plus_countries.v1.0.zip)

**Comment by jessespencersmith** [comment]
QWORD_2018_Core_10plus_countries(v1.0).csv
LAB_VAL_2018_Core_10plus_countries(v1.0).csv
in top-level project directory.
