### ISSUE TITLE
Simplify wording of categories, combine with column_names

### ISSUE THREAD

**Issue by jessespencersmith** [vanderbilt-data-science/lapop-dashboard#49]
Could we label columns as below? Can we shorten the categories to make it viable? Do we need to have a preceding number to present in a particular order?

The Economy-soct2
The Economy-idio2
The Economy-q10e
The Economy-fs2
The Economy-fs8
The Economy-ros4
The Economy-redist1
The Economy-redist2
The Economy-redist2a
The Economy-redist3
Civic and Political Engagement-cp2
Civic and Political Engagement-cp6
Civic and Political Engagement-cp7
Civic and Political Engagement-cp8
Civic and Political Engagement-cp13
Civic and Political Engagement-cp20
Civic and Political Engagement-prot3
Civic and Political Engagement-vb2
Civic and Political Engagement-vb10
Civic and Political Engagement-vb20
Local Government-np1
Local Government-sd2new2
Local Government-sd3new2
Local Government-sd6new2
Local Government-infrax
Evaluation of Institutions, Political   System and Other Persons-b1
Evaluation of Institutions, Political   System and Other Persons-b2
Evaluation of Institutions, Political   System and Other Persons-b3
Evaluation of Institutions, Political   System and Other Persons-b4
Evaluation of Institutions, Political   System and Other Persons-b6
Evaluation of Institutions, Political   System and Other Persons-b12
Evaluation of Institutions, Political   System and Other Persons-b13
Evaluation of Institutions, Political   System and Other Persons-b18
Evaluation of Institutions, Political   System and Other Persons-b20
Evaluation of Institutions, Political   System and Other Persons-b20a
Evaluation of Institutions, Political   System and Other Persons-b21
Evaluation of Institutions, Political   System and Other Persons-b21a
Evaluation of Institutions, Political   System and Other Persons-b31
Evaluation of Institutions, Political   System and Other Persons-b32
Evaluation of Institutions, Political   System and Other Persons-b37
Evaluation of Institutions, Political   System and Other Persons-b47a
Evaluation of Institutions, Political   System and Other Persons-m1
Evaluation of Institutions, Political   System and Other Persons-a4r
Evaluation of Institutions, Political   System and Other Persons-lib1
Evaluation of Institutions, Political   System and Other Persons-lib2c
Evaluation of Institutions, Political   System and Other Persons-eff1
Evaluation of Institutions, Political   System and Other Persons-eff2
Evaluation of Institutions, Political   System and Other Persons-it1
Support for Democracy and Democratic   Institutions-jc10
Support for Democracy and Democratic   Institutions-jc13
Support for Democracy and Democratic   Institutions-jc15a
Support for Democracy and Democratic   Institutions-jc16a
Support for Democracy and Democratic   Institutions-ing4
Support for Democracy and Democratic   Institutions-pn4
Crime, Insecurity, and Policy   Preferences-vic1ext
Crime, Insecurity, and Policy   Preferences-vic1exta
Crime, Insecurity, and Policy   Preferences-aoj11
Crime, Insecurity, and Policy   Preferences-aoj12
Corruption-exc2
Corruption-exc6
Corruption-exc20
Corruption-exc11
Corruption-exc13
Corruption-exc14
Corruption-exc15
Corruption-exc16
Corruption-exc18
Corruption-exc7
Corruption-exc7new
Political Tolerance-d1
Political Tolerance-d2
Political Tolerance-d3
Political Tolerance-d4
Political Tolerance-d5
Political Tolerance-d6
Political Tolerance-e5
Political/Electoral Engagement-pol1
Political/Electoral Engagement-gi0
Political/Electoral Engagement-gi0n
Political/Electoral Engagement-clien1n
Political/Electoral Engagement-clien1na
Migration-q10a
Migration-q14
Climate Change/Disaster Risk   Reduction-dst1b
Climate Change/Disaster Risk   Reduction-drk1
Climate Change/Disaster Risk   Reduction-env1c
Climate Change/Disaster Risk   Reduction-env2b
Gender-vb50
Gender-vb51
Gender-vb52
Gender-v58
Gender-w14a
Foreign Relations-mil10a
Foreign Relations-mil10e
Social Media-smedia1
Social Media-smedia4
Social Media-smedia7
Political and Religious Orientation-l1
Political and Religious Orientation-l1b
Political and Religious Orientation-q5a
Political and Religious Orientation-q5b
Political and Religious Orientation-q3cn
Sample Identification/Geographic-year
Sample Identification/Geographic-ur
Socio-Demographic Characteristics-q1
Socio-Demographic Characteristics-q2
Socio-Demographic Characteristics-ed
Socio-Demographic Characteristics-q10new
Socio-Demographic Characteristics-ocup4a
Socio-Demographic Characteristics-ocup1a
Socio-Demographic Characteristics-q11n
Socio-Demographic Characteristics-r3
Socio-Demographic Characteristics-r4
Socio-Demographic Characteristics-r4a
Socio-Demographic Characteristics-r5
Socio-Demographic Characteristics-r6
Socio-Demographic Characteristics-r7
Socio-Demographic Characteristics-r8
Socio-Demographic Characteristics-r12
Socio-Demographic Characteristics-r14
Socio-Demographic Characteristics-r15
Socio-Demographic Characteristics-r18
Socio-Demographic Characteristics-r1
Socio-Demographic Characteristics-r16
Socio-Demographic Characteristics-q12
Socio-Demographic Characteristics-q12bn
Socio-Demographic Characteristics-q12c
Socio-Demographic Characteristics-etid
Socio-Demographic Characteristics-leng1
Socio-Demographic Characteristics-wf1
Socio-Demographic Characteristics-cct1b

**Comment by jessespencersmith** [comment]
See if it is possible to have a reference for the questions--text box you can open? Side window? 
Preference would be to have it all! See the short question wording. Start with the full question, switch to short version when QWORD 2.0 is available. Find a way to:
1. Show category
2. Filter selections based on category
3. Show full/short question.

Suggestion from Maita, separate table to drive parameter/calc variable...

**Comment by jessespencersmith** [comment]
Research this and get report back later tonight.

**Comment by jessespencersmith** [comment]
Look in QWORD for shorter version, create new names for pivot_wider.

**Comment by jessespencersmith** [comment]
This will need to be more customized since aliases are only allowed for discrete dimensions, not measures. We can have a parameter-driven legend text. Need to decide where. Could do this next week.

**Comment by maitagorri** [comment]
Make category Spanish and shorter, make short wording (varlab) shorter

**Comment by mariana-rodriguez** [comment]
Here are two documents - one contains the short varlabs; the other the short category names. Let me know if one document would be better. Wasn't sure what would work best for @jessespencersmith 
[LAPOP_categories_numeric_es.xlsx](https://github.com/vanderbilt-data-science/lapop-dashboard/files/4300202/LAPOP_categories_numeric_es.xlsx)
[QWORD_2018_Core_10plus_countries(v2.0).xlsx](https://github.com/vanderbilt-data-science/lapop-dashboard/files/4300203/QWORD_2018_Core_10plus_countries.v2.0.xlsx)

**Comment by maitagorri** [comment]
We updated categories_numeric and questions_numeric. @jessespencersmith it'd be great if you can let us know if you need anything else from us.

**Comment by jessespencersmith** [comment]
@maitagorri @mariana-rodriguez  Excellent! I'll review now, and get to work!

**Comment by jessespencersmith** [comment]
@mariana-rodriguez Their are some questions missing categories:

a4	NA	
b0	NA	
formal	NA	
pra8n	NA	
vb58	NA

**Comment by jessespencersmith** [comment]
Parameter code is now generated in R, can copy and paste into Parameter creation dialog [Choose Variable]. Calculated field text is also generated in R (see NB 80), and can be pasted into a calculated filed code box [Variable].

**Comment by mariana-rodriguez** [comment]
@jessespencersmith do you still need categories for the variables you mention above?

**Comment by jessespencersmith** [comment]
@mariana-rodriguez Yes, please! I'm using "NA" right now

**Comment by maitagorri** [comment]
@jessespencersmith, does it make sense to keep [LAPOP_questions_numeric](https://github.com/vanderbilt-data-science/lapop-dashboard/blob/master/LAPOP_questions_numeric.csv) and [LAPOP_categories_numeric](https://github.com/vanderbilt-data-science/lapop-dashboard/blob/master/LAPOP_categories_numeric.csv) as the master documents, or would it make more sense to combine them into one lookup table (so when adding/removing variables it's immidiately clear that an update needs to happen to the categories)?

**Comment by maitagorri** [comment]
a4 should be a4r (now included as such in LAPOP_questions_numeric), b0 shouldn't be there at all, and formal, vb58 and pra8n have been added to LAPOP_categories_numeric

**Comment by jessespencersmith** [comment]
Need to read in new version of spreadsheet, but opening new issue #58
