### ISSUE TITLE
Haiti file not reading in

### ISSUE THREAD

**Issue by carmen-canedo** [vanderbilt-data-science/lapop-dashboard#8]
From the very beginning, Haiti has not read in

**Comment by maitagorri** [comment]
For data questions, get in touch with c.j.wilson@vanderbilt.edu

**Comment by jessespencersmith** [comment]
@carolejwilson, could I can a new export of the Haiti file? It is possible there was corruption of the file (or a change in structure). Anything different about Haiti that I should be aware of?

**Comment by carolejwilson** [comment]
Here's a link to the dataset: https://vanderbilt.box.com/s/384t8lkvq4yocskdfdy1mw6usr6edn44

**Comment by jessespencersmith** [comment]
This file is 2006-2017, unlike the other files. We'll need to check format and handle the processding separately. Let's put one of the students on this.
